Template.CustomTextInput.helpers(AccountsTemplates.atInputHelpers);
Template.CustomTextInput.events(AccountsTemplates.atInputEvents);
Template.CustomTextInput.helpers(AccountsTemplates.atInputHelpers);